/**
 * UGC Hoox - Form Handler
 * Handles FAQ accordion and contact form functionality
 * Integrates with Netlify Forms AND Supabase for submission
 *
 * Supabase setup:
 *   1. Create a "waitlist" table in your Supabase project with columns:
 *        id          (int8, primary key, generated by default)
 *        name        (text, not null)
 *        email       (text, not null)
 *        message     (text)
 *        created_at  (timestamptz, default: now())
 *   2. Set window.SUPABASE_URL and window.SUPABASE_ANON_KEY in index.html
 *      (the <script> block just above the JS file includes).
 *   3. In your Supabase dashboard → Authentication → Policies, make sure the
 *      "waitlist" table has an INSERT policy that allows anonymous inserts,
 *      or disable RLS on that table for public writes.
 */

(function() {
  'use strict';

  // ========== FAQ ACCORDION ==========

  /**
   * Initializes the FAQ accordion functionality
   */
  function initAccordion() {
    const questionItems = document.querySelectorAll('.question-item');

    if (questionItems.length === 0) {
      console.warn('No question items found');
      return;
    }

    questionItems.forEach(item => {
      const header = item.querySelector('.question-header');
      const toggleIcon = item.querySelector('.toggle-icon');

      if (!header) return;

      // Add click handler to the header
      header.addEventListener('click', () => {
        toggleAccordionItem(item);
      });

      // Ensure toggle icon doesn't double-trigger
      if (toggleIcon) {
        toggleIcon.addEventListener('click', (e) => {
          e.stopPropagation();
          toggleAccordionItem(item);
        });
      }
    });

    console.log(`Initialized ${questionItems.length} FAQ accordion items`);
  }

  /**
   * Toggles an accordion item open/closed
   */
  function toggleAccordionItem(item) {
    const isActive = item.classList.contains('active');

    // Optional: Close other items (remove if you want multiple items open)
    // closeAllAccordionItems();

    if (isActive) {
      // Close this item
      item.classList.remove('active');
    } else {
      // Open this item
      item.classList.add('active');

      // Smooth scroll to make sure the opened item is visible
      setTimeout(() => {
        const header = document.getElementById('header');
        const headerHeight = header ? header.offsetHeight : 0;
        const itemTop = item.offsetTop - headerHeight - 20;
        const currentScroll = window.scrollY;

        // Only scroll if the item is not fully visible
        if (currentScroll > itemTop) {
          window.scrollTo({
            top: itemTop,
            behavior: 'smooth'
          });
        }
      }, 300); // Wait for accordion animation
    }
  }

  /**
   * Closes all accordion items (optional - for single-open mode)
   */
  function closeAllAccordionItems() {
    const questionItems = document.querySelectorAll('.question-item');

    questionItems.forEach(item => {
      item.classList.remove('active');
    });
  }

  // ========== SUPABASE CLIENT ==========

  /**
   * Returns a Supabase client instance, or null if credentials are not yet
   * configured (i.e. the placeholders in index.html have not been replaced).
   * Safe to call multiple times — result is memoized.
   */
  var _supabaseClient = undefined; // undefined = not yet attempted

  function getSupabaseClient() {
    if (_supabaseClient !== undefined) return _supabaseClient;

    var url = window.SUPABASE_URL;
    var key = window.SUPABASE_ANON_KEY;

    if (
      !url || url === 'YOUR_SUPABASE_URL' ||
      !key || key === 'YOUR_SUPABASE_ANON_KEY'
    ) {
      console.warn(
        'Supabase credentials not configured. ' +
        'Set window.SUPABASE_URL and window.SUPABASE_ANON_KEY in index.html.'
      );
      _supabaseClient = null;
      return null;
    }

    if (!window.supabase || typeof window.supabase.createClient !== 'function') {
      console.warn('Supabase CDN script not loaded — skipping Supabase insert.');
      _supabaseClient = null;
      return null;
    }

    _supabaseClient = window.supabase.createClient(url, key);
    return _supabaseClient;
  }

  /**
   * Inserts one row into the "waitlist" table.
   * Returns a Promise that resolves on success and rejects on error.
   *
   * Expected table schema (Supabase / Postgres):
   *   id         bigint  generated by default as identity primary key
   *   name       text    not null
   *   email      text    not null
   *   message    text
   *   created_at timestamptz default now()
   */
  function submitToSupabase(name, email, message) {
    var client = getSupabaseClient();

    if (!client) {
      // Credentials not configured — resolve silently so Netlify path still works.
      return Promise.resolve({ skipped: true });
    }

    return client
      .from('waitlist')
      .insert([{ name: name, email: email, message: message }])
      .then(function(result) {
        if (result.error) {
          throw result.error;
        }
        console.log('Supabase insert succeeded.');
        return result;
      });
  }

  // ========== CONTACT FORM ==========

  /**
   * Initializes the contact form functionality
   */
  function initContactForm() {
    var contactForm = document.getElementById('contactForm');

    if (!contactForm) {
      console.warn('Contact form not found');
      return;
    }

    contactForm.addEventListener('submit', handleFormSubmit);

    // Add real-time validation
    var inputs = contactForm.querySelectorAll('.form-input, .form-textarea');
    inputs.forEach(function(input) {
      input.addEventListener('blur', function() { validateField(input); });
      input.addEventListener('input', function() { clearFieldError(input); });
    });

    console.log('Contact form initialized');
  }

  /**
   * Submits form data to Netlify Forms via URL-encoded POST.
   * Returns a Promise that resolves on HTTP 2xx, rejects otherwise.
   */
  function submitToNetlify(form, formObject) {
    var encode = function(data) {
      return Object.keys(data)
        .map(function(key) {
          return encodeURIComponent(key) + '=' + encodeURIComponent(data[key]);
        })
        .join('&');
    };

    return fetch(form.getAttribute('action') || '/', {
      method: 'POST',
      headers: { 'Content-Type': 'application/x-www-form-urlencoded' },
      body: encode(formObject)
    }).then(function(response) {
      if (!response.ok) {
        return response.text().then(function(text) {
          console.error('Netlify response:', text);
          throw new Error('Netlify submission failed (' + response.status + ')');
        });
      }
      console.log('Netlify Forms submission succeeded.');
      return response;
    });
  }

  /**
   * Handles contact form submission.
   * Fires both Netlify Forms and Supabase inserts in parallel.
   * Shows success if at least one destination accepted the data.
   * Shows an error only if both fail.
   */
  function handleFormSubmit(e) {
    e.preventDefault();

    var form = e.target;

    // Validate all fields
    var isValid = true;
    var fields = ['name', 'email', 'message'];

    fields.forEach(function(fieldName) {
      var field = form[fieldName];
      if (!validateField(field)) {
        isValid = false;
      }
    });

    if (!isValid) {
      showFormMessage('Please fix the errors above.', 'error');
      return;
    }

    // Show loading state
    var submitBtn = form.querySelector('button[type="submit"]');
    var originalBtnText = submitBtn.innerHTML;
    submitBtn.innerHTML = '<span class="btn-loader"><span class="dot"></span><span class="dot"></span><span class="dot"></span></span> Sending...';
    submitBtn.disabled = true;

    // Build plain object from FormData (includes form-name for Netlify)
    var formData = new FormData(form);
    var formObject = {};
    formData.forEach(function(value, key) {
      formObject[key] = value;
    });

    var name    = (formObject['name']    || '').trim();
    var email   = (formObject['email']   || '').trim();
    var message = (formObject['message'] || '').trim();

    // Fire both destinations in parallel; neither blocks the other
    Promise.allSettled([
      submitToNetlify(form, formObject),
      submitToSupabase(name, email, message)
    ]).then(function(results) {
      var netlifyResult  = results[0];
      var supabaseResult = results[1];

      var netlifyOk  = netlifyResult.status  === 'fulfilled';
      var supabaseOk = supabaseResult.status === 'fulfilled';

      if (netlifyResult.status === 'rejected') {
        console.error('Netlify error:', netlifyResult.reason);
      }
      if (supabaseResult.status === 'rejected') {
        console.error('Supabase error:', supabaseResult.reason);
      }

      if (netlifyOk || supabaseOk) {
        showFormMessage(
          'You\'re on the list! We\'ll be in touch soon.',
          'success'
        );
        form.reset();

        // Clear success styling from fields
        var inputs = form.querySelectorAll('.form-input, .form-textarea');
        inputs.forEach(function(input) { input.classList.remove('success'); });

        // Clear success message after 5 seconds
        setTimeout(hideFormMessage, 5000);
      } else {
        showFormMessage(
          'Oops! Something went wrong. Please try again or email us directly.',
          'error'
        );
      }
    })
    .finally(function() {
      submitBtn.innerHTML = originalBtnText;
      submitBtn.disabled = false;
    });
  }

  /**
   * Validates a form field
   */
  function validateField(field) {
    const value = field.value.trim();
    const fieldName = field.name;
    let isValid = true;
    let errorMessage = '';

    // Remove previous error state
    clearFieldError(field);

    // Required field validation
    if (!value) {
      isValid = false;
      errorMessage = 'This field is required.';
    }

    // Email validation
    if (fieldName === 'email' && value) {
      const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/;
      if (!emailRegex.test(value)) {
        isValid = false;
        errorMessage = 'Please enter a valid email address.';
      }
    }

    // Name validation (minimum length)
    if (fieldName === 'name' && value && value.length < 2) {
      isValid = false;
      errorMessage = 'Name must be at least 2 characters.';
    }

    // Message validation (minimum length)
    if (fieldName === 'message' && value && value.length < 10) {
      isValid = false;
      errorMessage = 'Message must be at least 10 characters.';
    }

    // Show error if invalid
    if (!isValid) {
      showFieldError(field, errorMessage);
    } else {
      field.classList.add('success');
      field.classList.remove('error');
    }

    return isValid;
  }

  /**
   * Shows an error for a specific field
   */
  function showFieldError(field, message) {
    field.classList.add('error');
    field.classList.remove('success');

    // Create or update error message
    let errorElement = field.parentElement.querySelector('.field-error');

    if (!errorElement) {
      errorElement = document.createElement('div');
      errorElement.classList.add('field-error');
      errorElement.style.color = 'var(--accent-red)';
      errorElement.style.fontSize = 'var(--text-sm)';
      errorElement.style.marginTop = 'var(--space-xs)';
      field.parentElement.appendChild(errorElement);
    }

    errorElement.textContent = message;
  }

  /**
   * Clears error state from a field
   */
  function clearFieldError(field) {
    field.classList.remove('error');

    const errorElement = field.parentElement.querySelector('.field-error');
    if (errorElement) {
      errorElement.remove();
    }
  }

  /**
   * Shows a form-level message
   */
  function showFormMessage(message, type) {
    const formMessage = document.getElementById('formMessage');

    if (!formMessage) return;

    formMessage.textContent = message;
    formMessage.className = 'form-message ' + type;
    formMessage.style.display = 'block';
  }

  /**
   * Hides the form message
   */
  function hideFormMessage() {
    const formMessage = document.getElementById('formMessage');

    if (!formMessage) return;

    formMessage.style.display = 'none';
    formMessage.textContent = '';
    formMessage.className = 'form-message';
  }

  // ========== ADDITIONAL FEATURES ==========

  /**
   * Auto-expands textarea as user types
   */
  function initAutoExpandTextarea() {
    const textareas = document.querySelectorAll('.form-textarea, .demo-textarea');

    textareas.forEach(textarea => {
      // Set initial height
      adjustTextareaHeight(textarea);

      // Adjust on input
      textarea.addEventListener('input', () => {
        adjustTextareaHeight(textarea);
      });
    });
  }

  /**
   * Adjusts textarea height based on content
   */
  function adjustTextareaHeight(textarea) {
    // Reset height to auto to get the correct scrollHeight
    textarea.style.height = 'auto';

    // Set new height (with max limit)
    const maxHeight = 400; // Maximum height in pixels
    const newHeight = Math.min(textarea.scrollHeight, maxHeight);

    textarea.style.height = newHeight + 'px';
  }

  /**
   * Adds character counter to textarea (optional)
   */
  function initCharacterCounter() {
    const messageField = document.getElementById('message');

    if (!messageField) return;

    const maxChars = 500; // Maximum character limit
    const counter = document.createElement('div');
    counter.classList.add('char-counter');
    counter.style.fontSize = 'var(--text-sm)';
    counter.style.color = 'var(--light-text)';
    counter.style.marginTop = 'var(--space-xs)';
    counter.style.textAlign = 'right';

    messageField.parentElement.appendChild(counter);

    function updateCounter() {
      const remaining = maxChars - messageField.value.length;
      counter.textContent = `${remaining} characters remaining`;

      if (remaining < 0) {
        counter.style.color = 'var(--accent-red)';
        messageField.value = messageField.value.substring(0, maxChars);
      } else if (remaining < 50) {
        counter.style.color = 'var(--accent-red)';
      } else {
        counter.style.color = 'var(--light-text)';
      }
    }

    messageField.addEventListener('input', updateCounter);
    updateCounter();
  }

  // ========== INITIALIZATION ==========

  /**
   * Initialize all form-related features
   */
  function init() {
    if (document.readyState === 'loading') {
      document.addEventListener('DOMContentLoaded', init);
      return;
    }

    console.log('Initializing form handlers...');

    initAccordion();
    initContactForm();
    initAutoExpandTextarea();

    // Optional: Uncomment to enable character counter
    // initCharacterCounter();

    console.log('Form handlers initialization complete!');
  }

  // Start initialization
  init();

})();
